name: flutter_marvel_characters
description: A Flutter app to list Marvel characters and show character details using Clean Architecture.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # HTTP client
  dio: ^5.7.0

  # State management (escolha profissional para Clean Architecture)
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5

  # Dependency Injection
  get_it: ^7.7.0

  # Env variables (guardar API keys sem expor no código)
  flutter_dotenv: ^5.1.0


  # UI improvements (não obrigatório, mas agrega)
  google_fonts: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Testes e mocks
  mocktail: ^1.0.3


flutter:
  uses-material-design: true

  assets:
    - .env
